import React from 'react';
import RizzlineTool from './RizzlineTool';
import { RIZZLINE_CATEGORIES, RIZZLINE_FAQS, RIZZLINE_GUIDANCE, RIZZLINE_LINKS, RIZZLINE_SEO } from './pageContent';

export default function RizzlinePage() {
  return <main className="marketing-container py-5 sm:py-8">
    <noscript><p className="mb-6 rounded-xl border border-pink-300/20 p-4 text-sm text-pink-100">Enable JavaScript to browse and save lines. You can still read the pickup line examples and advice below.</p></noscript>
    <nav aria-label="Breadcrumb" className="mb-4 text-xs text-white/60"><a href="/landing" className="hover:text-pink-200">Rizz Master</a><span aria-hidden="true"> / </span><span aria-current="page">Rizzline</span></nav>
    <section aria-labelledby="rizzline-heading"><h1 id="rizzline-heading" className="sr-only">{RIZZLINE_SEO.heading}</h1><RizzlineTool /></section>
    <section className="mx-auto mt-12 max-w-2xl rounded-2xl border border-white/10 bg-white/[0.03] p-6 text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-pink-200">Rizzline by Rizz Master</p><p className="mt-3 text-sm leading-7 text-white/65">Choose a line that fits the moment, watch how they respond and move into a real conversation. For a reply tailored to an actual chat, try Rizz Master Chat Reply.</p><a href="/" className="marketing-cta-primary mt-5 inline-flex min-h-[44px] items-center justify-center rounded-xl px-4 py-3 text-sm font-bold text-white">Need a tailored reply? →</a></section>
    <section className="mt-16 border-t border-white/10 pt-10" aria-labelledby="rizzline-how-heading"><h2 id="rizzline-how-heading" className="text-2xl font-bold sm:text-3xl">How to use pickup lines naturally</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{RIZZLINE_GUIDANCE.map((item, index) => <article key={item.title} className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><span className="text-xs font-bold text-pink-200">0{index + 1}</span><h3 className="mt-4 text-lg font-bold">{item.title}</h3><p className="mt-3 text-sm leading-7 text-white/65">{item.text}</p></article>)}</div></section>
    <section id="pickup-line-examples" className="mt-14 scroll-mt-6" aria-labelledby="rizzline-examples-heading"><h2 id="rizzline-examples-heading" className="text-2xl font-bold sm:text-3xl">Pickup line examples by vibe</h2><p className="mt-4 max-w-3xl text-base leading-7 text-white/65">Different moments call for different energy. These examples help you choose a starting point; the tool above lets you move through the catalog one line at a time.</p><div className="mt-7 grid gap-4 md:grid-cols-2">{RIZZLINE_CATEGORIES.map(item => <article key={item.id} id={`${item.id}-pickup-lines`} className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><h3 className="text-xl font-bold"><span aria-hidden="true">{item.emoji} </span>{item.label} pickup lines</h3><p className="mt-3 text-sm leading-7 text-white/65">{item.description}</p><ul className="mt-4 space-y-3">{item.examples.map(example => <li key={example} className="border-l-2 border-pink-300/40 pl-4 text-sm leading-7 text-white/85">“{example}”</li>)}</ul></article>)}</div></section>
    <section className="mt-14" aria-labelledby="rizzline-faq-heading"><h2 id="rizzline-faq-heading" className="text-2xl font-bold sm:text-3xl">Pickup line questions, answered</h2><div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.03] px-6">{RIZZLINE_FAQS.map(item => <details key={item.question} className="border-b border-white/10 py-5 last:border-0"><summary className="cursor-pointer text-base font-bold leading-7 text-white/90">{item.question}</summary><p className="mt-3 text-sm leading-7 text-white/65">{item.answer}</p></details>)}</div></section>
    <section className="mt-14 pb-5" aria-labelledby="rizzline-related-heading"><h2 id="rizzline-related-heading" className="text-2xl font-bold">Keep the conversation going</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{RIZZLINE_LINKS.map(item => <a key={item.href} href={item.href} className="rounded-2xl border border-pink-300/15 bg-pink-300/[0.04] p-6 transition-colors hover:border-pink-300/50"><h3 className="font-bold text-pink-100">{item.label} →</h3><p className="mt-3 text-sm leading-6 text-white/65">{item.description}</p></a>)}</div></section>
  </main>;
}
